export type BadgeTier = 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';

export interface BadgeDefinition {
  id: string;
  requiredDays: number;
  nameJa: string;
  nameEn: string;
  descriptionJa: string;
  tier: BadgeTier;
  iconName: string;
  gradientColors: string[];
}

export const BADGE_TIER_COLORS: Record<BadgeTier, string> = {
  bronze: '#CD7F32',
  silver: '#C0C0C0',
  gold: '#FFD700',
  platinum: '#E5E4E2',
  diamond: '#00D4FF',
};

export const BADGES: BadgeDefinition[] = [
  {
    id: 'fresh_start',
    requiredDays: 0,
    nameJa: '新しい始まり',
    nameEn: 'Fresh Start',
    descriptionJa: '最初の一歩を踏み出した。ここから全てが始まる。',
    tier: 'bronze',
    iconName: 'leaf-outline',
    gradientColors: ['#8B9DAF', '#4A6741'],
  },
  {
    id: 'first_light',
    requiredDays: 1,
    nameJa: '最初の光',
    nameEn: 'First Light',
    descriptionJa: '1日をクリアした。この勝利を忘れないで。',
    tier: 'bronze',
    iconName: 'sunny-outline',
    gradientColors: ['#FFE4A0', '#E8A030'],
  },
  {
    id: 'steady_step',
    requiredDays: 3,
    nameJa: '確かな一歩',
    nameEn: 'Steady Step',
    descriptionJa: '3日間、自分に勝ち続けた。力がついてきている。',
    tier: 'bronze',
    iconName: 'footsteps-outline',
    gradientColors: ['#7EC8A0', '#3A8B5C'],
  },
  {
    id: 'one_week',
    requiredDays: 7,
    nameJa: '一週間の壁',
    nameEn: 'One Week',
    descriptionJa: '最初の1週間を突破。脳の回復が始まっている。',
    tier: 'bronze',
    iconName: 'shield-checkmark-outline',
    gradientColors: ['#5BBBEF', '#2878B5'],
  },
  {
    id: 'rising_flame',
    requiredDays: 14,
    nameJa: '燃える意志',
    nameEn: 'Rising Flame',
    descriptionJa: '2週間継続。衝動のピークを乗り越えつつある。',
    tier: 'silver',
    iconName: 'flame-outline',
    gradientColors: ['#FF9A56', '#E85D30'],
  },
  {
    id: 'three_weeks',
    requiredDays: 21,
    nameJa: '習慣の芽',
    nameEn: 'Three Weeks',
    descriptionJa: '21日間。新しい習慣の基盤が形成されている。',
    tier: 'silver',
    iconName: 'leaf',
    gradientColors: ['#A8E06A', '#5BA02E'],
  },
  {
    id: 'one_month',
    requiredDays: 30,
    nameJa: '一ヶ月の証',
    nameEn: 'One Month',
    descriptionJa: '30日達成。ドーパミン受容体が回復し始めている。',
    tier: 'silver',
    iconName: 'medal-outline',
    gradientColors: ['#C0C8E0', '#8090B8'],
  },
  {
    id: 'resilient',
    requiredDays: 45,
    nameJa: '不屈の心',
    nameEn: 'Resilient',
    descriptionJa: '45日間の継続。困難を乗り越える力がついた。',
    tier: 'gold',
    iconName: 'fitness-outline',
    gradientColors: ['#FFD060', '#C89820'],
  },
  {
    id: 'two_months',
    requiredDays: 60,
    nameJa: '60日の道',
    nameEn: 'Two Months',
    descriptionJa: '2ヶ月達成。脳の配線が確実に変わり始めている。',
    tier: 'gold',
    iconName: 'heart',
    gradientColors: ['#FF7878', '#C83030'],
  },
  {
    id: 'reboot',
    requiredDays: 90,
    nameJa: 'リブート完了',
    nameEn: 'Reboot',
    descriptionJa: '90日達成。脳のリブートが完了。新しい自分へ。',
    tier: 'gold',
    iconName: 'refresh-circle',
    gradientColors: ['#00E5FF', '#0088CC'],
  },
  {
    id: 'iron_will',
    requiredDays: 120,
    nameJa: '鉄の意志',
    nameEn: 'Iron Will',
    descriptionJa: '120日間。もう後戻りはしない決意が固まった。',
    tier: 'platinum',
    iconName: 'barbell-outline',
    gradientColors: ['#B0B8C8', '#6070A0'],
  },
  {
    id: 'half_year',
    requiredDays: 180,
    nameJa: '半年の軌跡',
    nameEn: 'Half Year',
    descriptionJa: '半年を達成。あなたの変化は周りにも見えている。',
    tier: 'platinum',
    iconName: 'planet-outline',
    gradientColors: ['#E8A0FF', '#9040D0'],
  },
  {
    id: 'pioneer',
    requiredDays: 270,
    nameJa: '開拓者',
    nameEn: 'Pioneer',
    descriptionJa: '9ヶ月。未知の領域を開拓し続けている。',
    tier: 'platinum',
    iconName: 'compass-outline',
    gradientColors: ['#FFB830', '#E07000'],
  },
  {
    id: 'one_year',
    requiredDays: 365,
    nameJa: '一年の勲章',
    nameEn: 'One Year',
    descriptionJa: '1年間の継続。あなたは別人になった。',
    tier: 'platinum',
    iconName: 'trophy',
    gradientColors: ['#FFD700', '#B8860B'],
  },
  {
    id: 'fortress',
    requiredDays: 500,
    nameJa: '鉄壁の守り',
    nameEn: 'Fortress',
    descriptionJa: '500日。揺るぎない意志の砦を築いた。',
    tier: 'diamond',
    iconName: 'shield',
    gradientColors: ['#E0E8F0', '#A0B0D0'],
  },
  {
    id: 'two_years',
    requiredDays: 730,
    nameJa: '二年の偉業',
    nameEn: 'Two Years',
    descriptionJa: '2年間。あなたの回復は完全なものになりつつある。',
    tier: 'diamond',
    iconName: 'diamond-outline',
    gradientColors: ['#70E8FF', '#2090E0'],
  },
  {
    id: 'legend',
    requiredDays: 1000,
    nameJa: '伝説',
    nameEn: 'Legend',
    descriptionJa: '1000日達成。あなたの歩みは伝説となる。',
    tier: 'diamond',
    iconName: 'star',
    gradientColors: ['#FFE070', '#FF8C00', '#FF4500'],
  },
  {
    id: 'three_years',
    requiredDays: 1095,
    nameJa: '三年の王冠',
    nameEn: 'Three Years',
    descriptionJa: '3年間の継続。真の自由を手に入れた王者。',
    tier: 'diamond',
    iconName: 'crown-outline',
    gradientColors: ['#00F0FF', '#A855F7', '#EC4899'],
  },
];
