"""Resend transactional email sender.

Intentionally minimal Markdown → HTML conversion to avoid pulling in heavy
dependencies (the report we send is generated by Claude with predictable
structure: headings, paragraphs, and pipe tables).
"""
import html
import re
from typing import Optional

import requests


RESEND_ENDPOINT = "https://api.resend.com/emails"


def markdown_to_html(md: str) -> str:
    """Convert a small Markdown subset (h1/h2, paragraphs, tables) to HTML."""
    out_parts: list[str] = []
    buffer: list[str] = []
    in_table = False

    def flush_buffer():
        if not buffer:
            return
        text = "\n".join(buffer).strip()
        if text:
            out_parts.append(f"<p>{html.escape(text)}</p>")
        buffer.clear()

    def flush_table():
        nonlocal in_table
        if buffer:
            out_parts.append("<pre>" + html.escape("\n".join(buffer)) + "</pre>")
            buffer.clear()
        in_table = False

    for line in md.splitlines():
        stripped = line.rstrip()
        is_table_line = stripped.startswith("|") and stripped.endswith("|")

        if is_table_line:
            if not in_table:
                flush_buffer()
                in_table = True
            buffer.append(stripped)
            continue

        if in_table:
            flush_table()

        if stripped.startswith("## "):
            flush_buffer()
            out_parts.append(f"<h2>{html.escape(stripped[3:])}</h2>")
        elif stripped.startswith("# "):
            flush_buffer()
            out_parts.append(f"<h1>{html.escape(stripped[2:])}</h1>")
        elif not stripped:
            flush_buffer()
        else:
            buffer.append(stripped)

    if in_table:
        flush_table()
    else:
        flush_buffer()

    return "\n".join(out_parts)


def send_email(
    api_key: str,
    sender: str,
    recipient: str,
    subject: str,
    markdown_body: str,
) -> Optional[str]:
    """Send a single email via Resend. Returns the Resend message ID on 2xx.

    Raises:
        RuntimeError: on non-2xx response from Resend.
    """
    payload = {
        "from": sender,
        "to": recipient,
        "subject": subject,
        "text": markdown_body,
        "html": markdown_to_html(markdown_body),
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    resp = requests.post(RESEND_ENDPOINT, json=payload, headers=headers)
    if not (200 <= resp.status_code < 300):
        body = resp.text
        try:
            body = resp.json()
        except Exception:
            pass
        raise RuntimeError(f"Resend send failed ({resp.status_code}): {body}")
    return resp.json().get("id")
