import type { BadgeId } from './BadgeId';
import type { ChapterId } from './BadgeChapter';
import type { BadgeColorTriad } from './BadgeColorTriad';

export interface NeuralBadgeDefinition {
  readonly id: BadgeId;
  readonly day: number;
  readonly chapter: ChapterId;
  readonly nameJa: string;
  readonly nameEn: string;
  readonly message: string;
  readonly visual: string;
  readonly neural: string;
  readonly colors: BadgeColorTriad;
}

export const BADGE_DEFINITIONS: readonly NeuralBadgeDefinition[] = [
  // ── Chapter 1: Chaos (混沌) ──
  {
    id: 'Stardust',
    day: 0,
    chapter: 'chaos',
    nameJa: '星屑',
    nameEn: 'Stardust',
    message: '宇宙の始まり。あなたの意志が最初の光を放った。',
    visual: '淡い銀色の粒子が漂う',
    neural: '決意の瞬間 — 前頭前皮質が新しいパターンを開始',
    colors: { core: '#C9CBE0', glow: '#F5F6FA', accent: '#9E8CC4' },
  },
  {
    id: 'Nebula',
    day: 1,
    chapter: 'chaos',
    nameJa: '星雲',
    nameEn: 'Nebula',
    message: 'ガスと塵が集まり始めた。最初の一歩。',
    visual: '紫がかった雲が渦を巻く',
    neural: '最初の24時間 — ドーパミン受容体が回復を開始',
    colors: { core: '#B8A9D4', glow: '#E8E0F0', accent: '#7B68AE' },
  },
  {
    id: 'Protostar',
    day: 3,
    chapter: 'chaos',
    nameJa: '原始星',
    nameEn: 'Protostar',
    message: '重力が物質を引き寄せ、核が形成され始めた。',
    visual: 'ぼんやりと光るコア',
    neural: '3日目 — 離脱症状のピークを越え始める',
    colors: { core: '#D4C5A0', glow: '#F0E8D0', accent: '#A89060' },
  },
  // ── Chapter 2: Ignition (点火) ──
  {
    id: 'Ignition',
    day: 7,
    chapter: 'ignition',
    nameJa: '点火',
    nameEn: 'Ignition',
    message: '核融合が始まった。あなたの中に恒星が誕生した。',
    visual: 'オレンジの炎が噴き出す',
    neural: '1週間 — 前頭前皮質の灰白質密度が増加傾向',
    colors: { core: '#FFB547', glow: '#FFE4A0', accent: '#FF7847' },
  },
  {
    id: 'MainSequence',
    day: 14,
    chapter: 'ignition',
    nameJa: '主系列星',
    nameEn: 'Main Sequence',
    message: '安定した輝きを得た。習慣の炎が灯り続ける。',
    visual: '安定した黄色い光球',
    neural: '2週間 — セロトニン系が正常化し始める',
    colors: { core: '#FFD700', glow: '#FFF3B0', accent: '#E6A800' },
  },
  {
    id: 'Radiance',
    day: 21,
    chapter: 'ignition',
    nameJa: '輝光',
    nameEn: 'Radiance',
    message: '光はさらに強まり、周囲を照らし始めた。',
    visual: '眩い白金色の光',
    neural: '3週間 — 新しい神経回路が定着し始める',
    colors: { core: '#FFF0C0', glow: '#FFFDE8', accent: '#FFD060' },
  },
  // ── Chapter 3: Formation (形成) ──
  {
    id: 'AccretionDisk',
    day: 30,
    chapter: 'formation',
    nameJa: '降着円盤',
    nameEn: 'Accretion Disk',
    message: '重力が物質を集め、惑星系の種が回り始めた。',
    visual: '回転するオレンジの円盤',
    neural: '1ヶ月 — 前頭前皮質-線条体接続が強化',
    colors: { core: '#D17842', glow: '#F4C58A', accent: '#8B3A0F' },
  },
  {
    id: 'Planetesimal',
    day: 45,
    chapter: 'formation',
    nameJa: '微惑星',
    nameEn: 'Planetesimal',
    message: '小さな天体が合体を繰り返し、成長している。',
    visual: '岩石が集まる微惑星',
    neural: '45日 — ストレス応答システムが再調整される',
    colors: { core: '#A0785A', glow: '#D4B896', accent: '#6B4226' },
  },
  {
    id: 'PlanetaryBirth',
    day: 60,
    chapter: 'formation',
    nameJa: '惑星誕生',
    nameEn: 'Planetary Birth',
    message: '原始惑星が誕生した。新しい世界の始まり。',
    visual: '溶岩に覆われた原始惑星',
    neural: '2ヶ月 — デフォルトモードネットワークが再構成',
    colors: { core: '#C45030', glow: '#F0A080', accent: '#802010' },
  },
  // ── Chapter 4: Life (生命) ──
  {
    id: 'HabitableWorld',
    day: 90,
    chapter: 'life',
    nameJa: '生命圏',
    nameEn: 'Habitable World',
    message: '水が流れ、大気が安定した。生命が宿れる星になった。',
    visual: '青い海と緑の大地',
    neural: '90日 — 脳の報酬系がほぼ正常化',
    colors: { core: '#4A90E2', glow: '#A8D8F0', accent: '#2B5F9E' },
  },
  {
    id: 'Biogenesis',
    day: 120,
    chapter: 'life',
    nameJa: '生命の起源',
    nameEn: 'Biogenesis',
    message: '最初の生命が海から生まれた。あなたの中に新しい力が芽生える。',
    visual: '海中に光る原始生命',
    neural: '4ヶ月 — 意志力の自動化が進む',
    colors: { core: '#2ECC71', glow: '#A8F0C8', accent: '#1A7A42' },
  },
  {
    id: 'Civilization',
    day: 180,
    chapter: 'life',
    nameJa: '文明',
    nameEn: 'Civilization',
    message: '知性が花開き、星を見上げる文明が生まれた。',
    visual: '夜景に輝く都市の光',
    neural: '半年 — 新しい習慣が第二の天性になる',
    colors: { core: '#8B5CF6', glow: '#D4B8FF', accent: '#5B21B6' },
  },
  // ── Chapter 5: Expansion (拡張) ──
  {
    id: 'SolarSystem',
    day: 270,
    chapter: 'expansion',
    nameJa: '太陽系',
    nameEn: 'Solar System',
    message: '恒星と惑星が調和し、1つの系を成した。',
    visual: '惑星が軌道を描く太陽系',
    neural: '9ヶ月 — 自己制御が生活全般に波及',
    colors: { core: '#5CE1E6', glow: '#B8F5F7', accent: '#1E6B7F' },
  },
  {
    id: 'BinaryStars',
    day: 365,
    chapter: 'expansion',
    nameJa: '連星',
    nameEn: 'Binary Stars',
    message: '2つの恒星が互いを照らし合う。1年の軌跡。',
    visual: '対になって輝く二重星',
    neural: '1年 — 脳構造の永続的変化が確認される時期',
    colors: { core: '#00D4FF', glow: '#80ECFF', accent: '#0088AA' },
  },
  {
    id: 'StarCluster',
    day: 500,
    chapter: 'expansion',
    nameJa: '星団',
    nameEn: 'Star Cluster',
    message: '数百の星が集い、壮大な星団を形成した。',
    visual: '密集する青白い星々',
    neural: '500日 — 新しい神経ネットワークが完全に定着',
    colors: { core: '#38BDF8', glow: '#BAE6FD', accent: '#0284C7' },
  },
  // ── Chapter 6: Transcendence (超越) ──
  {
    id: 'Galaxy',
    day: 730,
    chapter: 'transcendence',
    nameJa: '銀河',
    nameEn: 'Galaxy',
    message: '数千億の星が渦巻く銀河。2年の偉業。',
    visual: '渦巻く銀河のアーム',
    neural: '2年 — 完全な脳の再配線が達成される',
    colors: { core: '#EC4899', glow: '#FBCFE8', accent: '#831843' },
  },
  {
    id: 'GalaxyCluster',
    day: 1000,
    chapter: 'transcendence',
    nameJa: '銀河団',
    nameEn: 'Galaxy Cluster',
    message: '銀河が集い、宇宙の大規模構造を描く。',
    visual: '連なる銀河のフィラメント',
    neural: '1000日 — あなたは完全に変わった',
    colors: { core: '#A855F7', glow: '#E9D5FF', accent: '#6B21A8' },
  },
  {
    id: 'Cosmos',
    day: 1095,
    chapter: 'transcendence',
    nameJa: '宇宙',
    nameEn: 'Cosmos',
    message: '全てを包む宇宙そのもの。あなたは宇宙になった。',
    visual: '無限に広がる宇宙全体',
    neural: '3年 — 脳は完全に新しいあなたのもの',
    colors: { core: '#F43F5E', glow: '#FFE4E8', accent: '#9F1239' },
  },
];
