import type { BadgeId } from './BadgeId';
import type { ChapterId } from './BadgeChapter';
import type { BadgeColorTriad } from './BadgeColorTriad';

export interface NeuralBadgeDefinition {
  readonly id: BadgeId;
  readonly day: number;
  readonly chapter: ChapterId;
  readonly nameJa: string;
  readonly nameEn: string;
  readonly message: string;
  readonly visual: string;
  readonly neural: string;
  readonly colors: BadgeColorTriad;
}

export const BADGE_DEFINITIONS: readonly NeuralBadgeDefinition[] = [
  // ── Chapter 1: Birth (誕生) ──
  {
    id: 'stardust',
    day: 0,
    chapter: 'birth',
    nameJa: '星屑',
    nameEn: 'Stardust',
    message: '宇宙の始まり。あなたの意志が最初の光を放った。',
    visual: '淡い銀色の粒子が漂う',
    neural: '決意の瞬間 — 前頭前皮質が新しいパターンを開始',
    colors: { core: '#C9CBE0', mid: '#D8D9EA', outer: '#9E8CC4', glow: '#F5F6FA' },
  },
  {
    id: 'nebula',
    day: 1,
    chapter: 'birth',
    nameJa: '星雲',
    nameEn: 'Nebula',
    message: 'ガスと塵が集まり始めた。最初の一歩。',
    visual: '紫がかった雲が渦を巻く',
    neural: '最初の24時間 — ドーパミン受容体が回復を開始',
    colors: { core: '#B8A9D4', mid: '#D0C4E4', outer: '#7B68AE', glow: '#E8E0F0' },
  },
  {
    id: 'protostar',
    day: 3,
    chapter: 'birth',
    nameJa: '原始星',
    nameEn: 'Protostar',
    message: '重力が物質を引き寄せ、核が形成され始めた。',
    visual: 'ぼんやりと光るコア',
    neural: '3日目 — 離脱症状のピークを越え始める',
    colors: { core: '#D4C5A0', mid: '#E2D8BC', outer: '#A89060', glow: '#F0E8D0' },
  },
  // ── Chapter 2: Inner Planets (内惑星) ──
  {
    id: 'moon',
    day: 7,
    chapter: 'innerPlanets',
    nameJa: '月',
    nameEn: 'Moon',
    message: '静かな光が闇を照らす。最初の1週間を越えた。',
    visual: '銀白色のクレーター付き球体',
    neural: '1週間 — 前頭前皮質の灰白質密度が増加傾向',
    colors: { core: '#D4D4D8', mid: '#E8E8EC', outer: '#9CA3AF', glow: '#F4F4F5' },
  },
  {
    id: 'mercury',
    day: 14,
    chapter: 'innerPlanets',
    nameJa: '水星',
    nameEn: 'Mercury',
    message: '太陽に最も近い惑星。灼熱を超えて前進する。',
    visual: '灰褐色の岩石惑星',
    neural: '2週間 — セロトニン系が正常化し始める',
    colors: { core: '#A8A29E', mid: '#C4BFB9', outer: '#78716C', glow: '#D6D3D1' },
  },
  {
    id: 'venus',
    day: 21,
    chapter: 'innerPlanets',
    nameJa: '金星',
    nameEn: 'Venus',
    message: '厚い雲の下に隠された輝き。3週間の成長。',
    visual: '黄白色の厚い大気に包まれた惑星',
    neural: '3週間 — 新しい神経回路が定着し始める',
    colors: { core: '#F5DEB3', mid: '#FAE8C8', outer: '#D4A76A', glow: '#FFF8E7' },
  },
  // ── Chapter 3: Terrestrial (地球型惑星) ──
  {
    id: 'earth',
    day: 30,
    chapter: 'terrestrial',
    nameJa: '地球',
    nameEn: 'Earth',
    message: '生命を育む青い星。1ヶ月の大きな節目。',
    visual: '青い海と白い雲の惑星',
    neural: '1ヶ月 — 前頭前皮質-線条体接続が強化',
    colors: { core: '#4A90E2', mid: '#6DB3F0', outer: '#2B5F9E', glow: '#A8D8F0' },
  },
  {
    id: 'mars',
    day: 45,
    chapter: 'terrestrial',
    nameJa: '火星',
    nameEn: 'Mars',
    message: '赤い大地に刻まれた峡谷。不屈の意志。',
    visual: '赤褐色の砂漠惑星',
    neural: '45日 — ストレス応答システムが再調整される',
    colors: { core: '#C1440E', mid: '#D4734A', outer: '#8B2500', glow: '#F0A080' },
  },
  {
    id: 'jupiter',
    day: 60,
    chapter: 'terrestrial',
    nameJa: '木星',
    nameEn: 'Jupiter',
    message: '太陽系最大の巨人。圧倒的な存在感。',
    visual: '縞模様と大赤斑の巨大ガス惑星',
    neural: '2ヶ月 — デフォルトモードネットワークが再構成',
    colors: { core: '#D4A574', mid: '#E2C4A0', outer: '#A0714A', glow: '#F0D8B8' },
  },
  // ── Chapter 4: Outer Planets (外惑星) ──
  {
    id: 'saturn',
    day: 90,
    chapter: 'outerPlanets',
    nameJa: '土星',
    nameEn: 'Saturn',
    message: '壮麗な環をまとう惑星。90日の偉業。',
    visual: '黄金色の環に囲まれた惑星',
    neural: '90日 — 脳の報酬系がほぼ正常化',
    colors: { core: '#E8C87A', mid: '#F0DCA0', outer: '#C4A050', glow: '#FFF0C0' },
  },
  {
    id: 'uranus',
    day: 120,
    chapter: 'outerPlanets',
    nameJa: '天王星',
    nameEn: 'Uranus',
    message: '横倒しの軸で自転する独特の星。唯一無二の道。',
    visual: '淡い水色の氷惑星',
    neural: '4ヶ月 — 意志力の自動化が進む',
    colors: { core: '#7DD3E8', mid: '#A0E4F0', outer: '#4AA8C0', glow: '#C8F0F8' },
  },
  {
    id: 'neptune',
    day: 180,
    chapter: 'outerPlanets',
    nameJa: '海王星',
    nameEn: 'Neptune',
    message: '深い青の嵐が渦巻く。半年の深い変化。',
    visual: '深い青色の嵐の惑星',
    neural: '半年 — 新しい習慣が第二の天性になる',
    colors: { core: '#3B5CE6', mid: '#6B82F0', outer: '#1E3AAA', glow: '#B0C0FF' },
  },
  // ── Chapter 5: Stellar (恒星) ──
  {
    id: 'sun',
    day: 270,
    chapter: 'stellar',
    nameJa: '太陽',
    nameEn: 'Sun',
    message: '全てを照らす恒星。9ヶ月の輝き。',
    visual: 'コロナを放つ黄金の恒星',
    neural: '9ヶ月 — 自己制御が生活全般に波及',
    colors: { core: '#FFD700', mid: '#FFE44D', outer: '#E6A800', glow: '#FFF3B0' },
  },
  {
    id: 'whiteDwarf',
    day: 365,
    chapter: 'stellar',
    nameJa: '白色矮星',
    nameEn: 'White Dwarf',
    message: '凝縮された輝き。1年の軌跡が結晶化した。',
    visual: '小さく超高密度に輝く白い星',
    neural: '1年 — 脳構造の永続的変化が確認される時期',
    colors: { core: '#E8E8F0', mid: '#F0F0FA', outer: '#B0B0D0', glow: '#FAFAFE' },
  },
  {
    id: 'stellarSystem',
    day: 500,
    chapter: 'stellar',
    nameJa: '恒星系',
    nameEn: 'Stellar System',
    message: '恒星と惑星が調和し、1つの系を成した。',
    visual: '複数の惑星が軌道を描く恒星系',
    neural: '500日 — 新しい神経ネットワークが完全に定着',
    colors: { core: '#5CE1E6', mid: '#80EAF0', outer: '#1E6B7F', glow: '#B8F5F7' },
  },
  // ── Chapter 6: Cosmic (宇宙) ──
  {
    id: 'starCluster',
    day: 730,
    chapter: 'cosmic',
    nameJa: '星団',
    nameEn: 'Star Cluster',
    message: '数百の星が集い、壮大な星団を形成した。',
    visual: '密集する青白い星々',
    neural: '2年 — 完全な脳の再配線が達成される',
    colors: { core: '#38BDF8', mid: '#60CCF8', outer: '#0284C7', glow: '#BAE6FD' },
  },
  {
    id: 'galaxy',
    day: 1000,
    chapter: 'cosmic',
    nameJa: '銀河',
    nameEn: 'Galaxy',
    message: '数千億の星が渦巻く銀河。1000日の偉業。',
    visual: '渦巻く銀河のアーム',
    neural: '1000日 — あなたは完全に変わった',
    colors: { core: '#A855F7', mid: '#C084FC', outer: '#6B21A8', glow: '#E9D5FF' },
  },
  {
    id: 'cosmos',
    day: 1095,
    chapter: 'cosmic',
    nameJa: '宇宙',
    nameEn: 'Cosmos',
    message: '全てを包む宇宙そのもの。あなたは宇宙になった。',
    visual: '無限に広がる宇宙全体',
    neural: '3年 — 脳は完全に新しいあなたのもの',
    colors: { core: '#F43F5E', mid: '#FB7185', outer: '#9F1239', glow: '#FFE4E8' },
  },
];
